---
- hosts: localhost
  connection: local
  become: yes
  vars:
    admin_user: root
    docker_required_packages:
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "gnupg-agent"
      - "software-properties-common"
      - "python3-pip"
      - "python3-setuptools"
    docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
    docker_repo: deb https://download.docker.com/linux/ubuntu bionic stable
    docker_packges:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: "Install required packages for docker"
      apt:
        name: "{{ docker_required_packages }}"
        state: latest
        update_cache: yes
        force_apt_get: yes
    - name: "Add Docker GPG key"
      apt_key:
        url: "{{ docker_gpg_url }}"
        state: present
    - name: "Add Docker Repository" 
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present
    - name: "Install Docker"
      apt:
        name: "{{ docker_packges }}"
        state: latest 
        update_cache: yes
    - name: "Install Python Docker Module"
      pip: 
        name: docker
    - name: "Install docker compose"
      apt: 
        name: docker-compose
        update_cache: yes
        force_apt_get: yes

